FROM node:23-alpine

# Install dependencies for development
RUN apk add --no-cache libc6-compat git python3 make g++

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /frontend

# Copy package files from frontend directory
COPY ./frontend/package.json ./frontend/pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install

# Copy frontend source code
COPY ./frontend .

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]
