FROM node:23-alpine

# Install dependencies for development
RUN apk add --no-cache libc6-compat git python3 make g++

WORKDIR /frontend

# Copy package files from frontend directory
COPY ./frontend/package.json ./frontend/yarn.lock* ./frontend/package-lock.json* ./

# Install dependencies
RUN \
  if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install; \
  elif [ -f package-lock.json ]; then npm install; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Copy frontend source code
COPY ./frontend .

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]
